### ISSUE TITLE
原型继承语言相对类继承语言而言有何缺点呢？

### ISSUE THREAD

**Issue by elvinlife** [compiler-teamwork-group09/python3-proto#1]

**Comment by songchaow** [comment]
从设计上说，原型继承语言中的一切事物均为对象，这对让初学者感到不适应。
在实现原型继承时，该语言往往得使用解释性的语言和动态弱类型系统，这两点造成了程序执行效率变低和安全性的降低。而类继承语言，则完全可以做到编译执行和静态强类型。
